# Generated by Django 4.2.7 on 2023-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='project_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
