# Generated by Django 4.2.7 on 2023-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_date', models.CharField(max_length=100)),
                ('project_id', models.BigIntegerField()),
                ('holiday_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('attachments_id', models.BigIntegerField()),
                ('task', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('start_time', models.CharField(blank=True, max_length=100)),
                ('end_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timesheet',
                'managed': True,
            },
        ),
    ]
