# Generated by Django 4.2.7 on 2023-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'occupation_user',
                'managed': True,
            },
        ),
    ]
