# Generated by Django 4.2.7 on 2023-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0002_occupationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationuser',
            name='occupation_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='occupationuser',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
